import {FaceView,CanvasFaceView,demoMesh,meshFromLandmarks,clamp} from './engine.js';
import {inspectPhoto,optionsForConcern} from './skin.js';
import {strings,topics} from './content.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const state={lang:'ko',points:[],selected:-1,gel:'1',product:'Alpha',slots:[null,null,null],slot:0,photo:false,source:null,pendingCanvas:null,quality:null,tab:'shape',before:false,busy:false,epoch:0,status:'ready'};
const langIndex=()=>({ko:0,en:1,zh:2}[state.lang]||0),tr=key=>strings[key]?.[langIndex()]||key;
let view,modelPromise;
function status(key,type=''){state.status=key;$('#status').textContent=tr(key);$('.statusbar').className='statusbar '+type;}
function translate(){document.documentElement.lang=state.lang;all('[data-t]').forEach(el=>el.textContent=tr(el.dataset.t));$('#model-label').textContent=tr(state.photo?'modelPhoto':'modelDemo');$('#status').textContent=tr(state.status);renderPoints();renderSlots();renderSkin();}
function modeTab(tab){state.tab=tab;const shape=tab==='shape';$('#shape-panel').hidden=!shape;$('#skin-panel').hidden=shape;for(const name of ['shape','skin']){const b=$('#'+name+'-tab');b.classList.toggle('active',name===tab);b.setAttribute('aria-selected',String(name===tab));}if(view){view.mode=0;view.update(state.points,!shape||state.before);$('#clay').setAttribute('aria-pressed','false');}all('[data-map]').forEach(b=>b.classList.toggle('active',b.dataset.map==='0'));const showBefore=!shape||state.before;$('#before').classList.toggle('active',showBefore);$('#after').classList.toggle('active',!showBefore);$('#before').setAttribute('aria-pressed',String(showBefore));$('#after').setAttribute('aria-pressed',String(!showBefore));$('#before').disabled=!shape;$('#after').disabled=!shape;$('#clay').disabled=!shape;}
function setBefore(value){state.before=value;$('#before').classList.toggle('active',value);$('#before').setAttribute('aria-pressed',String(value));$('#after').classList.toggle('active',!value);$('#after').setAttribute('aria-pressed',String(!value));view?.update(state.points,value);}
function renderPoints(){const box=$('#points');box.replaceChildren();if(!state.points.length){const p=document.createElement('p');p.textContent=tr('emptyPoints');box.append(p);}state.points.forEach((p,i)=>{const b=document.createElement('button');b.textContent=`${i+1} · ${p.product} · ${p.strength}`;b.className=i===state.selected?'active':'';b.setAttribute('aria-label',`${tr('point')} ${i+1}`);b.setAttribute('aria-pressed',String(i===state.selected));b.onclick=()=>{state.selected=i;$('#strength').value=p.strength;$('#strength-value').textContent=p.strength;$('#product').value=state.product=p.product;renderPoints();};box.append(b);});$('#undo').disabled=!state.points.length;$('#reset').disabled=!state.points.length;}
function updateShape(){if(!view)return;view.update(state.points,state.tab==='skin'||state.before);renderPoints();}
function addPoint(x,y){if(!view||state.tab!=='shape'||state.busy)return;const p=view.pick(x,y);if(!p)return;if(state.points.length>=8){status('limit');return;}state.points.push({...p,strength:Number($('#strength').value),product:state.product,gel:state.gel});state.selected=state.points.length-1;setBefore(false);updateShape();}
function pickGel(id){state.gel=id;all('[data-gel]').forEach(b=>b.classList.toggle('active',b.dataset.gel===id));}
function flatSnapshot(){view.draw();const c=document.createElement('canvas');c.width=360;c.height=420;const ctx=c.getContext('2d');ctx.fillStyle='#ece5dc';ctx.fillRect(0,0,c.width,c.height);const src=view.canvas,scale=Math.min(c.width/src.width,c.height/src.height),w=src.width*scale,h=src.height*scale;ctx.drawImage(src,(c.width-w)/2,(c.height-h)/2,w,h);return c.toDataURL('image/jpeg',.8);}
function renderSlots(){all('[data-slot]').forEach((el,i)=>{el.replaceChildren();const b=document.createElement('b');b.textContent='ABC'[i];el.append(b);const slot=state.slots[i];if(slot){const img=document.createElement('img');img.src=slot.thumbnail;img.alt=`${'ABC'[i]} · ${tr('after')}`;el.append(img);}else{const s=document.createElement('span');s.textContent=tr('empty');el.append(s);}el.setAttribute('aria-label',`${'ABC'[i]} · ${slot?tr('after'):tr('empty')}`);});}
const concerns=()=>all('input[name=concern]:checked').map(el=>el.value);
function renderSkin(){const q=state.quality;$('#no-skin').hidden=!!q;$('#skin-readout').hidden=!q;if(q){$('#quality').textContent=tr(q.ok?'qualityOk':'qualityBad');$('#quality').className='quality '+(q.ok?'':'bad');all('[data-map]').forEach(b=>b.disabled=b.dataset.map!=='0'&&!q.ok);}const risk=$('#risk').value,chosen=concerns(),box=$('#options');box.replaceChildren();if(risk!=='no'||!chosen.length){const p=document.createElement('p');p.className=risk==='yes'?'warning':'small';p.textContent=tr(risk==='yes'?'riskBlock':risk==='unknown'?'riskWait':'chooseConcern');box.append(p);return;}for(const item of optionsForConcern(topics,chosen,risk)){const card=document.createElement('article');card.className='topic';const title=document.createElement('h4'),body=document.createElement('p'),question=document.createElement('p'),a=document.createElement('a');title.textContent=item.title[langIndex()];body.textContent=item.body[langIndex()];question.textContent=item.question[langIndex()];question.className='question';a.href=item.url;a.textContent=tr('source');a.target='_blank';a.rel='noopener noreferrer';card.append(title,body,question,a);box.append(card);}}
function releasePhoto(){if(state.pendingCanvas){state.pendingCanvas.width=1;state.pendingCanvas.height=1;state.pendingCanvas=null;}if(state.source){state.source.width=1;state.source.height=1;}state.source=null;state.photo=false;state.quality=null;state.points=[];state.selected=-1;state.slots=[null,null,null];state.slot=0;state.before=false;all('input[name=concern]').forEach(c=>c.checked=false);$('#risk').value='unknown';$('#photo').value='';view?.setMesh(demoMesh());view?.resetCamera();$('#wire').setAttribute('aria-pressed','false');if(view)view.wire=false;$('#model-label').textContent=tr('modelDemo');renderSlots();renderPoints();renderSkin();modeTab('shape');setBefore(false);}
function setBusy(b){state.busy=b;$('#upload').disabled=b||!$('#consent').checked;$('#save').disabled=b||!view;$('#download').disabled=b||!view;}
const frame=()=>new Promise(resolve=>requestAnimationFrame(()=>resolve()));
async function loadModel(){if(!modelPromise)modelPromise=(async()=>{
 // Pinned historical SDK version; no user data is included in these requests.
 const base='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.21';
 const {FaceLandmarker,FilesetResolver}=await import(`${base}/vision_bundle.mjs`);
 const files=await FilesetResolver.forVisionTasks(`${base}/wasm`);
 return FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'CPU'},runningMode:'IMAGE',numFaces:2,minFaceDetectionConfidence:.7,minFacePresenceConfidence:.7,outputFaceBlendshapes:false,outputFacialTransformationMatrixes:false});
 })().catch(error=>{modelPromise=null;throw error;});return modelPromise;}
function timeout(p,ms){let timer;return Promise.race([p,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('model-timeout')),ms))]).finally(()=>clearTimeout(timer));}
async function decodePhoto(file){const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();if(!img.width||!img.height||img.width*img.height>40000000)throw Error('file');const scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c;}finally{img.src='';URL.revokeObjectURL(url);}}
async function processPhoto(file){if(!$('#consent').checked||!view)return;if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024){status('fileError','error');$('#photo').value='';return;}const token=++state.epoch;releasePhoto();setBusy(true);let canvas;
 try{canvas=await decodePhoto(file);if(token!==state.epoch)return;state.pendingCanvas=canvas;status('loading','busy');const model=await timeout(loadModel(),45000);if(token!==state.epoch)return;status('scanning','busy');await frame();await frame();if(token!==state.epoch)return;const result=model.detect(canvas);if(result.faceLandmarks.length!==1)throw Error('face');const lm=result.faceLandmarks[0],pts=lm.slice(0,468),width=(Math.max(...pts.map(p=>p.x))-Math.min(...pts.map(p=>p.x)))*canvas.width;if(width<150||pts.some(p=>p.x<.005||p.x>.995||p.y<.005||p.y>.995))throw Error('small');const mesh=meshFromLandmarks(lm,canvas.width,canvas.height);if(token!==state.epoch)return;
 state.source=canvas;state.pendingCanvas=null;state.photo=true;state.quality=inspectPhoto(canvas,lm);view.setMesh(mesh,canvas);view.setSignals(state.quality.signal);view.resetCamera();$('#model-label').textContent=tr('modelPhoto');$('#geometry-count').textContent=`${mesh.positions.length/3} VERTICES / ${mesh.indices.length/3} TRIANGLES`;renderSkin();status('loaded');
 }catch(error){if(token!==state.epoch)return;const key=error.message==='face'?'faceError':error.message==='small'?'photoSmall':error.message==='file'||error.name==='EncodingError'?'fileError':'loadError';status(key,'error');}finally{if(canvas&&canvas!==state.source){canvas.width=1;canvas.height=1;}if(token===state.epoch){state.pendingCanvas=null;setBusy(false);}}
}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportComparison(){if(!view||state.busy)return;const was={before:state.before,mode:view.mode,yaw:view.yaw,pitch:view.pitch,zoom:view.zoom};view.mode=0;view.resetCamera();const out=document.createElement('canvas');out.width=1400;out.height=960;const ctx=out.getContext('2d');ctx.fillStyle='#f2ece5';ctx.fillRect(0,0,1400,960);ctx.fillStyle='#292b42';ctx.font='26px sans-serif';ctx.fillText('AESTYVE / 3D FACE LAB',40,49);ctx.font='17px sans-serif';ctx.fillText(state.photo?'PHOTO-BASED ESTIMATED SURFACE':'DEMO MODEL - NOT YOUR FACE',40,82);
 for(let i=0;i<2;i++){view.update(state.points,i===0);const src=view.canvas,s=Math.min(640/src.width,730/src.height),w=src.width*s,h=src.height*s;ctx.drawImage(src,i*700+(700-w)/2,130+(730-h)/2,w,h);ctx.fillStyle='#292b42';ctx.font='20px sans-serif';ctx.fillText(i?'VISUAL SIMULATION':'ORIGINAL SHAPE',i*700+40,124);}
 ctx.fillStyle='#292b42';ctx.fillRect(0,870,1400,90);ctx.fillStyle='#fff';ctx.font='19px sans-serif';ctx.fillText('VISUAL SIMULATION ONLY - NOT A TREATMENT RESULT OR MEDICAL PLAN',35,907);ctx.font='16px sans-serif';ctx.fillText('Estimated front surface. No diagnosis, treatment recommendation, injection volume or depth.',35,938);
 view.yaw=was.yaw;view.pitch=was.pitch;view.zoom=was.zoom;view.mode=was.mode;view.update(state.points,was.before);out.toBlob(blob=>{if(blob)downloadBlob(blob,'Aestyve-visual-comparison.png');},'image/png');}
function exportNotes(){const chosen=concerns(),risk=$('#risk').value;const data={schema:'aestyve-discussion-notes/1',createdAt:new Date().toISOString(),language:state.lang,purpose:'User-selected concerns and educational topics; NOT a diagnosis or treatment plan.',notice:tr('footer'),selfReportedConcerns:chosen.map(k=>tr(k)),selfReportedSafety:risk,safetyMessage:tr(risk==='yes'?'riskBlock':risk==='no'?'riskNotClearance':'riskWait'),captureChecks:state.quality?{passedBasicChecks:state.quality.ok,note:tr('qualityWhy')}:null,educationalTopics:optionsForConcern(topics,chosen,risk).map(t=>({title:t.title[langIndex()],information:t.body[langIndex()],question:t.question[langIndex()],source:t.url})),notIncluded:['photo','face landmarks','diagnosis','recommended treatment','dose','skin score']};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'Aestyve-discussion-notes.json');status('reportDone');}
try{try{view=new FaceView($('#face3d'));}catch(webglError){const replacement=$('#face3d').cloneNode(true);$('#face3d').replaceWith(replacement);view=new CanvasFaceView(replacement);$('#engine-mode').textContent='SOFTWARE / 3D';}$('#geometry-count').textContent=`${view.base.length/3} VERTICES / ${view.mesh.indices.length/3} TRIANGLES`;}catch(e){status('webglError','error');$('#consent').disabled=true;all('#shape-panel button,#skin-panel [data-map],.view-tools button,.view-switch button,#wire').forEach(b=>b.disabled=true);}
$('#language').onchange=e=>{state.lang=e.target.value;translate();};
$('#consent').onchange=()=>{if(!$('#consent').checked){++state.epoch;releasePhoto();status('eraseDone');}setBusy(false);};
$('#upload').onclick=()=>$('#photo').click();$('#photo').onchange=e=>processPhoto(e.target.files[0]);
$('#erase').onclick=()=>{++state.epoch;releasePhoto();$('#consent').checked=false;setBusy(false);status('eraseDone');};
$('#shape-tab').onclick=()=>modeTab('shape');$('#skin-tab').onclick=()=>modeTab('skin');
$('#before').onclick=()=>setBefore(true);$('#after').onclick=()=>setBefore(false);
$('#wire').onclick=()=>{if(!view)return;view.wire=!view.wire;$('#wire').setAttribute('aria-pressed',String(view.wire));view.draw();};
$('#home').onclick=()=>view?.resetCamera();$('#clay').onclick=()=>{if(!view)return;view.mode=view.mode===3?0:3;$('#clay').setAttribute('aria-pressed',String(view.mode===3));view.draw();};
const zoom=d=>{if(view){view.zoom=clamp(view.zoom+d,.7,1.8);view.draw();}};$('#zoom-in').onclick=()=>zoom(.1);$('#zoom-out').onclick=()=>zoom(-.1);
$('#product').onchange=e=>{state.product=e.target.value;if(state.points[state.selected]){state.points[state.selected].product=state.product;renderPoints();}};
$('#strength').oninput=e=>{const n=Number(e.target.value);$('#strength-value').textContent=n;if(state.points[state.selected]){state.points[state.selected].strength=n;setBefore(false);updateShape();}};
$('#undo').onclick=()=>{state.points.pop();state.selected=state.points.length-1;updateShape();};$('#reset').onclick=()=>{state.points=[];state.selected=-1;updateShape();};
$('#save').onclick=()=>{if(!view||state.busy)return;setBefore(false);view.mode=0;view.draw();state.slots[state.slot%3]={points:structuredClone(state.points),thumbnail:flatSnapshot()};state.slot++;renderSlots();status('saved');};
all('[data-slot]').forEach(b=>b.onclick=()=>{const slot=state.slots[Number(b.dataset.slot)];if(!slot||!view)return;state.points=structuredClone(slot.points);state.selected=state.points.length-1;modeTab('shape');setBefore(false);if(state.selected>=0){const p=state.points[state.selected];$('#strength').value=p.strength;$('#strength-value').textContent=p.strength;$('#product').value=state.product=p.product;}updateShape();});
$('#download').onclick=exportComparison;$('#report').onclick=exportNotes;
all('[data-map]').forEach(b=>b.onclick=()=>{if(!view||!state.photo||!state.quality)return;const mode=Number(b.dataset.map);if(mode&&!state.quality.ok)return;all('[data-map]').forEach(x=>x.classList.toggle('active',x===b));view.mode=mode;view.update(state.points,true);});
all('input[name=concern]').forEach(c=>c.onchange=renderSkin);$('#risk').onchange=renderSkin;
const canvas=$('#face3d');let pointer=null;
canvas.onpointerdown=e=>{if(!view)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!pointer||pointer.id!==e.pointerId||!view)return;const dx=e.clientX-pointer.lastX,dy=e.clientY-pointer.lastY;if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>5)pointer.moved=true;if(pointer.moved){view.yaw=clamp(view.yaw+dx*.007,-.70,.70);view.pitch=clamp(view.pitch+dy*.005,-.36,.36);view.draw();}pointer.lastX=e.clientX;pointer.lastY=e.clientY;};
canvas.onpointerup=e=>{if(pointer?.id!==e.pointerId)return;if(!pointer.moved)addPoint(e.clientX,e.clientY);pointer=null;};canvas.onpointercancel=()=>pointer=null;
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?-.05:.05);},{passive:false});
canvas.onkeydown=e=>{if(!view)return;let handled=true;if(e.key==='ArrowLeft')view.yaw=clamp(view.yaw-.08,-.70,.70);else if(e.key==='ArrowRight')view.yaw=clamp(view.yaw+.08,-.70,.70);else if(e.key==='ArrowUp')view.pitch=clamp(view.pitch-.06,-.36,.36);else if(e.key==='ArrowDown')view.pitch=clamp(view.pitch+.06,-.36,.36);else if(e.key==='+')zoom(.1);else if(e.key==='-')zoom(-.1);else if(e.key==='Enter'){const r=canvas.getBoundingClientRect();addPoint(r.left+r.width/2,r.top+r.height*.58);}else handled=false;if(handled){e.preventDefault();view.draw();}};
canvas.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';};canvas.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/aestyve-gel');if(['1','2','3'].includes(id)){pickGel(id);addPoint(e.clientX,e.clientY);}};
all('[data-gel]').forEach(b=>{b.onclick=()=>pickGel(b.dataset.gel);b.ondragstart=e=>{pickGel(b.dataset.gel);e.dataTransfer.setData('text/aestyve-gel',b.dataset.gel);e.dataTransfer.effectAllowed='copy';};let ghost=null,start=null;
 b.onpointerdown=e=>{if(e.pointerType==='mouse')return;pickGel(b.dataset.gel);start={x:e.clientX,y:e.clientY};b.setPointerCapture(e.pointerId);};b.onpointermove=e=>{if(!start)return;if(!ghost&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>6){ghost=b.querySelector('img').cloneNode();ghost.className='drag-ghost';document.body.append(ghost);}if(ghost){ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';}};b.onpointerup=e=>{if(ghost){const r=canvas.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)addPoint(e.clientX,e.clientY);ghost.remove();}ghost=null;start=null;};b.onpointercancel=()=>{ghost?.remove();ghost=null;start=null;};});
fetch('./gels.json').then(r=>{if(!r.ok)throw Error('assets');return r.json();}).then(gels=>all('[data-gel]').forEach(b=>{b.querySelector('img').src=gels[b.dataset.gel];})).catch(()=>{all('.gel img').forEach(img=>img.hidden=true);});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();status('webglError','error');$('#upload').disabled=true;});
window.addEventListener('pagehide',()=>{++state.epoch;releasePhoto();const pending=modelPromise;modelPromise=null;pending?.then(m=>m.close()).catch(()=>{});});
translate();setBusy(false);if(!view)status('webglError','error');
