export const strings={
 lab:['3D 얼굴 탐색 · 개발 프리뷰','3D face exploration · development preview','3D 面部探索 · 开发预览'],
 title:['내 얼굴을,\n내 시선으로.','Your face.\nYour perspective.','我的面容，\n我的视角。'],
 intro:['누군가의 권유보다, 내가 원하는 변화를 먼저 탐색하세요.','Explore what you want, before considering anyone’s suggestion.','先了解自己的想法，再考虑他人的建议。'],
 shapeTab:['3D 형태 탐색','3D shape studio','3D 形态探索'],skinTab:['피부 관찰 · 치료 정보','Skin notes · treatment information','皮肤观察 · 治疗信息'],
 privacyTitle:['내 사진은 내 기기에','Your photo stays on your device','照片留在本机'],
 privacy:['사진·랜드마크·설문은 이 페이지의 메모리에서 처리하며 서버에 보내지 않습니다. 모델·폰트 다운로드 시 외부 CDN에 접속합니다. 사진 변경·삭제·새로고침으로 세션 데이터가 사라집니다. 직접 내려받은 파일은 기기에 남습니다.','Photos, landmarks and answers are processed in page memory, not sent to a server. Model and font downloads contact external CDNs. Replacing, deleting or refreshing clears session data. Files you explicitly download remain on your device.','照片、关键点和问卷仅在页面内存中处理，不上传服务器。模型与字体下载会连接外部 CDN。更换、删除或刷新页面会清除会话数据，主动下载的文件仍保留在本机。'],
 consent:['성인이며, 본인 사진을 위 방식으로 처리하는 데 동의합니다.','I am an adult and consent to processing my own photo as described.','我是成年人，同意按上述方式处理本人的照片。'],
 upload:['내 사진으로 3D 만들기','Create 3D from my photo','用我的照片创建 3D'],
 photoGuide:['정면 · 표정은 편안하게 · 균일한 조명 · 필터·화장 없이. JPG/PNG/WebP, 최대 12MB.','Front-facing, neutral expression, even lighting, no filters or makeup. JPG/PNG/WebP, up to 12MB.','正面、自然表情、光线均匀、无滤镜或化妆。JPG/PNG/WebP，最大 12MB。'],
 erase:['사진·결과 모두 지우기','Clear photo & all results','清除照片与全部结果'],
 modelDemo:['샘플 3D · 내 얼굴 아님','Demo 3D · not your face','示例 3D · 非本人面容'],modelPhoto:['사진 기반 추정 3D','Photo-based estimated 3D','照片估算的 3D'],
 meshNote:['전면 표면만 복원 · 깊이는 추정값 · 뒤통수·피부 속은 복원하지 않음','Front surface only · estimated depth · no back-of-head or internal anatomy','仅重建正面表面 · 深度为估算值 · 不包含后脑及内部组织'],
 before:['원본 형태','Original shape','原始形态'],after:['내 시뮬레이션','My simulation','我的模拟'],wire:['메시 보기','Wireframe','网格'],clay:['표면 보기','Clay surface','表面模式'],home:['정면','Front','正面'],
 rotateHint:['드래그: 회전 · 휠/확대 버튼: 확대 · 얼굴 탭: 조절점 추가','Drag to rotate · wheel/zoom buttons to zoom · tap the face to add a shape point','拖动旋转 · 滚轮/按钮缩放 · 点击面部添加形态点'],
 shapeTitle:['원하는 변화를 탐색하세요','Explore a change','探索想要的变化'],
 product:['제품 라벨','Product label','产品标签'],
 gelTitle:['겔 사진을 얼굴로 드래그','Drag a gel photo onto the face','将凝胶照片拖到面部'],
 gelNote:['첨부 순서의 겔 원본입니다. 사진↔Alpha/Beta/Gamma 대응은 미확정이며, 제품별 물성·효과 차이는 반영하지 않습니다.','Reference photos in attachment order. Mapping to Alpha/Beta/Gamma is unconfirmed; no product-specific material or effect differences are modelled.','按附件顺序展示的凝胶原图。与 Alpha/Beta/Gamma 的对应关系尚未确认，未模拟产品物性或效果差异。'],
 strength:['형태 변화 강도','Shape-change intensity','形态变化强度'],
 units:['시각화 단위 · 시술 용량 아님','visual units · not treatment volume','视觉单位 · 非治疗剂量'],
 noMl:['mL와 실제 얼굴 변화를 연결하는 검증 모델이 없어, 이번 버전은 주입량·주입 깊이를 제시하지 않습니다.','There is no validated link between mL and facial change in this model. It provides neither injection volumes nor injection depths.','本模型尚未验证毫升数与面部变化的关系，因此不提供注射量或注射深度。'],
 points:['형태 조절점','Shape points','形态调节点'],point:['조절점','Point','调节点'],emptyPoints:['얼굴을 탭하거나 겔을 드래그하세요. 최대 8개.','Tap the face or drag a gel onto it. Up to 8 points.','点击面部或拖入凝胶，最多 8 个点。'],
 undo:['마지막 점 지우기','Undo last point','撤销最后一个点'],reset:['변화 초기화','Reset changes','重置变化'],save:['현재 안 저장','Save this look','保存当前方案'],empty:['비어 있음','Empty','空'],
 saved:['비교 안을 메모리에 저장했어요. 썸네일을 누르면 복원됩니다.','Look saved in memory. Select its thumbnail to restore it.','方案已保存在内存中，点击缩略图即可恢复。'],
 download:['비교 이미지 저장','Download comparison image','保存对比图'],
 footer:['시각화·정보 탐색용 개발 프리뷰입니다. 실제 시술 결과, 진단, 피부검사, 안전성 판정 또는 치료 필요성·용량을 제공하지 않습니다. 시술하지 않는 선택도 가능합니다.','Development preview for visualization and information. Not a treatment outcome prediction, diagnosis, skin examination, safety clearance, or decision about treatment need or dose. No treatment is also a valid choice.','本开发预览仅用于可视化和信息探索，不预测实际治疗结果，不进行诊断、皮肤检查、安全判定，也不决定治疗必要性或剂量。不接受治疗同样是可选项。'],
 ready:['샘플 3D를 먼저 돌려보세요. 사진 분석은 동의 후 시작합니다.','Rotate the demo 3D first. Photo analysis starts only after consent.','先旋转示例 3D，照片分析仅在同意后开始。'],
 loading:['얼굴 모델을 불러오는 중… 사진은 전송되지 않습니다.','Loading the face model… your photo is not transmitted.','正在加载面部模型…照片不会上传。'],
 scanning:['기기 안에서 얼굴 랜드마크를 추정하는 중…','Estimating face landmarks on your device…','正在本机估算面部关键点…'],
 loaded:['추정 3D를 만들었어요. 좌우로 돌려서 확인하세요.','Estimated 3D is ready. Rotate it to inspect the surface.','估算 3D 已生成，请旋转查看表面。'],
 loadError:['얼굴 모델을 불러오지 못했습니다. 인터넷·CDN 차단 여부를 확인하고 다시 시도하세요. 사진은 전송하지 않았습니다. 샘플 3D는 계속 사용할 수 있습니다.','The face model could not load. Check your connection or CDN blocking and try again. No photo was transmitted. Demo 3D remains available.','面部模型加载失败。请检查网络或 CDN 拦截后重试。照片未上传，示例 3D 仍可使用。'],
 fileError:['12MB 이하의 JPG/PNG/WebP 사진을 선택하세요. HEIC는 JPG로 변환해 주세요.','Choose a JPG/PNG/WebP photo up to 12MB. Convert HEIC to JPG first.','请选择 12MB 以下的 JPG/PNG/WebP 照片，HEIC 请先转换为 JPG。'],
 faceError:['정면 얼굴 한 명을 확인할 수 없습니다. 다른 사진으로 다시 시도하세요. 피부 결과는 생성하지 않았습니다.','One front-facing face could not be confirmed. Try another photo. No skin result was generated.','无法确认单人的正面面容，请更换照片。未生成皮肤结果。'],
 photoSmall:['얼굴이 너무 작거나 잘렸습니다. 얼굴 전체가 크게 보이는 정면 사진을 사용하세요.','The face is too small or cropped. Use a larger, full, front-facing portrait.','面部过小或被裁切，请使用完整且清晰的正面照片。'],
 eraseDone:['사진·랜드마크·비교 안·설문을 지웠어요. 다운로드 파일은 직접 삭제해야 합니다.','Photo, landmarks, saved looks and answers cleared. Delete downloaded files separately.','照片、关键点、比较方案和问卷已清除。已下载的文件需自行删除。'],
 limit:['조절점은 최대 8개입니다. 기존 점을 선택해 바꾸세요.','Up to 8 shape points. Select an existing point to edit.','最多 8 个调节点，请选择现有点进行修改。'],
 skinTitle:['사진으로 볼 수 있는 것부터','Start with what a photo can show','从照片可见的信息开始'],
 skinIntro:['이 기능은 피부검사가 아닙니다. 원본 사진의 색상 차이를 참고하고, 스스로 느끼는 고민을 기록하세요.','This is not a skin examination. Explore color differences in the original photo and record your own concerns.','此功能并非皮肤检查。可参考原始照片的颜色差异，并记录自己的困扰。'],
 noSkin:['본인 사진을 추가하면 촬영 품질과 색상 참고 지도를 확인할 수 있습니다. 샘플 얼굴에는 피부 결과를 만들지 않습니다.','Add your own photo to inspect capture quality and a reference color map. No skin result is created for the demo.','添加本人照片后可查看拍摄质量与颜色参考图。示例面容不生成皮肤结果。'],
 qualityTitle:['촬영 상태 참고','Capture checks','拍摄状态参考'],qualityOk:['기본 촬영 조건 통과 · 임상 신뢰도와 무관','Basic capture checks passed · not clinical confidence','通过基本拍摄检查 · 不代表临床可靠性'],
 qualityBad:['측정 대신 재촬영 권장 · 색상 지도 잠금','Retake photo · color maps disabled','建议重拍 · 颜色图已锁定'],
 qualityWhy:['사진의 노출·얼굴 크기·기울기를 단순 검사합니다. 화장·필터·피부질환·피부톤 편향을 모두 검출하지 못합니다.','Simple exposure, face-size and tilt checks cannot detect every filter, makeup effect, skin condition or skin-tone bias.','仅简单检查曝光、面部大小和倾斜，无法检测全部滤镜、化妆、皮肤状况或肤色偏差。'],
 originalMap:['원본 색상','Original color','原始颜色'],redMap:['상대적 붉은 색상','Relative red color','相对红色'],toneMap:['상대적 명암','Relative light / dark','相对明暗'],
 legend:['차가운 색: 사진 내부 상대적으로 낮음 · 따뜻한 색: 높음 · 무색: 평가 제외','Cool: lower relative image signal · warm: higher · uncolored: excluded','冷色：照片内相对较低 · 暖色：相对较高 · 无色：不作评估'],
 mapNote:['원본 사진의 볼·이마 일부에서 색상만 비교합니다. 조명·그림자·화장도 포함됩니다. 붉은 색은 염증 진단이 아니며 어두운 색은 기미 진단이 아닙니다. 다른 사람·촬영일의 결과와 비교할 수 없습니다.','Only color in limited cheek/forehead patches of the original image is compared. Lighting, shadows and makeup also affect it. Red does not diagnose inflammation; darkness does not diagnose melasma. Do not compare across people or capture dates.','仅比较原始照片部分面颊及额头的颜色，也会受光线、阴影和化妆影响。红色不代表炎症诊断，暗色不代表黄褐斑诊断。不可跨人或跨拍摄日期比较。'],
 notMeasured:['측정하지 않음: 수분·유분·탄력·콜라겐·피부 나이·기미·모공 등급. 피부 내부나 질환은 사진만으로 확정하지 않습니다.','Not measured: hydration, oil, elasticity, collagen, skin age, melasma or pore grades. Internal skin properties and disease are not established from a photo.','不测量水分、油脂、弹性、胶原蛋白、皮肤年龄、黄褐斑或毛孔等级。不凭照片确定皮肤内部状态或疾病。'],
 concernTitle:['내가 느끼는 고민','My own concerns','我自己的困扰'],
 dry:['건조함·당김','Dryness / tightness','干燥 / 紧绷'],red:['붉어 보임','Visible redness','看起来发红'],pigment:['색소·색상 차이','Pigment / color differences','色素 / 色差'],texture:['피부결·잔주름','Texture / fine lines','肤质 / 细纹'],
 safety:['현재 다음 중 해당하는 것이 있나요?','Do any of the following apply now?','目前有以下情况吗？'],
 risk:['통증·진물·상처, 빠르게 변하거나 피가 나는 병변, 최근 시술 후 이상 반응이 있음','Pain, oozing, wounds, rapidly changing or bleeding lesions, or a reaction after a recent procedure','疼痛、渗液、伤口、快速变化或出血的皮损，或近期治疗后的异常反应'],
 riskUnknown:['아직 답하지 않음 / 잘 모르겠음','Not answered / unsure','尚未回答 / 不确定'],riskNo:['위 항목은 없다고 응답함','I report none of these','我报告无以上情况'],riskYes:['해당 항목이 있음','One or more apply','有以上情况'],
 riskBlock:['사진으로 판단하지 마세요. 치료 옵션보다 의료진의 진료가 우선입니다. 시술 후 심한 통증·시력 변화 등 급한 증상은 즉시 의료기관에 연락하세요.','Do not rely on a photo. Seek medical assessment before exploring procedures. Severe pain or vision changes after a procedure require immediate medical attention.','不要依靠照片判断，应先接受医疗评估。治疗后严重疼痛或视力变化等急症需立即就医。'],
 riskNotClearance:['해당 사항이 없다는 응답만으로 안전성·적합성이 확인되는 것은 아닙니다. 병력·복용약·알레르기·최근 시술 등을 의료진과 확인하세요.','Reporting none does not establish safety or suitability. Review medical history, medications, allergies and recent procedures with a clinician.','报告无上述情况并不代表安全或适合，应与医疗人员核对病史、用药、过敏及近期治疗。'],
 riskWait:['안전 질문에 먼저 답하세요. 이 질문은 전체 금기사항 검사나 안전성 확인을 대신하지 않습니다.','Answer the safety question first. It does not replace a full contraindication assessment or establish safety.','请先回答安全问题，此问题不能代替完整的禁忌症评估或确认安全性。'],
 optionsTitle:['비수술 치료 정보','Non-surgical treatment information','非手术治疗信息'],
 optionsNote:['사진 점수로 고른 추천이 아닙니다. 선택한 고민에 연결된 일반 정보이며, 적합 여부·기기·제품·횟수·용량을 정하지 않습니다. 시술하지 않기·기본 관리도 함께 검토하세요.','These are general topics linked to concerns you selected, not photo-based recommendations. No suitability, device, product, session count or dose is determined. Also consider no procedure and basic care.','这些是与您选择的困扰相关的一般信息，并非基于照片评分的推荐。不决定适用性、设备、产品、次数或剂量。也请考虑不做治疗和基础护理。'],
 chooseConcern:['고민을 선택하면 관련 설명과 진료 시 확인할 질문이 나타납니다.','Select a concern to see information and questions for a clinician.','选择困扰后可查看相关说明和就诊时的问题。'],
 source:['근거 보기','Read source','查看来源'],report:['사진 없는 상담 메모 저장','Save photo-free discussion notes','保存不含照片的咨询记录'],
 reportDone:['상담 메모를 저장했어요. 의료적 치료계획이 아닙니다.','Discussion notes saved. This is not a medical treatment plan.','咨询记录已保存，并非医疗治疗方案。'],
 reference:['일반 정보 출처 · 개별 제품의 한국 허가를 뜻하지 않음','General information sources · not Korean authorization of any product','一般信息来源 · 不代表任何产品在韩国获批'],
 previewOnly:['환자 공개 전 검증 필요','Validation required before patient launch','患者公开使用前须验证'],
 webglError:['이 브라우저에서 3D를 시작하지 못했습니다. WebGL을 지원하는 최신 브라우저를 사용하세요.','3D could not start. Use a current browser with WebGL enabled.','3D 无法启动，请使用支持 WebGL 的新版浏览器。'],
 zoomIn:['확대','Zoom in','放大'],zoomOut:['축소','Zoom out','缩小']
};
export const topics=[
 {id:'care',concerns:['dry','red','pigment','texture'],title:['시술하지 않기 · 기본 피부관리','No procedure · basic skin care','不做治疗 · 基础皮肤护理'],body:['보습·자극 최소화·자외선 차단과 진료만으로 관리하는 선택도 있습니다. 건조함이 있다고 주사가 필수인 것은 아닙니다.','Moisturizing, reducing irritation, sun protection and clinical care without a procedure are also options. Dryness does not make injections necessary.','也可选择保湿、减少刺激、防晒及不进行操作的医疗护理。干燥并不意味着必须注射。'],question:['원인을 먼저 확인해야 하나요? 기본 관리만으로 관찰해도 될까요?','Should the cause be assessed first? Can we start with basic care alone?','应先确认原因吗？是否可以先仅进行基础护理？'],url:'https://www.aad.org/public/everyday-care/skin-care-basics/dry/dermatologists-tips-relieve-dry-skin'},
 {id:'light',concerns:['red'],title:['혈관 레이저 · 광치료 정보','Vascular laser · light therapy information','血管激光 · 光治疗信息'],body:['일부 홍조·혈관 고민에 사용되는 치료가 있지만 붉은 색의 원인은 다릅니다. 적합성 평가가 먼저이며, 화상·색소 변화 등의 위험을 확인해야 합니다.','These treatments are used for some redness or visible-vessel concerns, but causes vary. Suitability assessment comes first, including risks such as burns and pigment changes.','这些治疗用于部分发红或可见血管问题，但原因各异。应先评估适用性，包括灼伤和色素变化等风险。'],question:['주사·피부염 등 원인 감별이 필요한가요? 내 피부톤에서 위험은 어떤가요?','Does rosacea, dermatitis or another cause need evaluation? What are the risks for my skin tone?','是否需要鉴别玫瑰痤疮、皮炎等原因？对我的肤色有何风险？'],url:'https://www.aad.org/public/diseases/rosacea/treatment/lasers-lights'},
 {id:'pigment',concerns:['pigment'],title:['색소 고민 · 레이저 전 원인 확인','Pigment concerns · assessment before lasers','色素问题 · 激光前确认原因'],body:['기미·염증 후 색소 변화·다른 병변은 접근이 다릅니다. 광치료·레이저가 항상 첫 선택은 아니며 오히려 색소 변화가 심해질 수 있습니다.','Melasma, post-inflammatory color changes and other lesions need different approaches. Laser or light therapy is not always first-line and can worsen pigmentation.','黄褐斑、炎症后色素变化及其他皮损的处理不同。激光或光治疗并非总是首选，也可能加重色素变化。'],question:['정확히 어떤 종류의 색소인가요? 바르는 치료나 관찰이 대안인가요?','What type of pigment change is it? Are topical treatment or observation alternatives?','具体是哪种色素变化？外用治疗或观察是否可替代？'],url:'https://www.aad.org/public/diseases/a-z/melasma-treatment'},
 {id:'resurface',concerns:['texture'],title:['피부결 · 미세침 치료 정보','Texture · microneedling information','肤质 · 微针治疗信息'],body:['일부 피부결·흉터 고민에서 의료적 미세침 치료를 논의할 수 있습니다. 회복기간·감염·색소 변화·흉터 위험과 적합성을 확인해야 합니다. RF 미세침은 일반 미세침과 같지 않습니다.','Medical microneedling may be discussed for some texture or scar concerns. Review downtime, infection, pigment changes, scarring and suitability. RF microneedling is not the same as conventional microneedling.','部分肤质或瘢痕问题可讨论医疗微针治疗，需确认恢复期、感染、色素变化、瘢痕风险及适用性。射频微针不等同于普通微针。'],question:['시술 없이 관리할 수 있나요? 내 병력에서 피해야 할 치료가 있나요?','Can this be managed without a procedure? Does my history make any treatment unsuitable?','能否不做操作来管理？我的病史中有不适合的治疗吗？'],url:'https://www.fda.gov/medical-devices/aesthetic-cosmetic-devices/microneedling-devices'},
 {id:'booster',concerns:['dry','texture'],title:['물광주사 · 스킨부스터를 묻는다면','Questions about skin boosters / “hydration injections”','关于水光针 / 皮肤增强剂的问题'],body:['이 명칭은 하나의 표준 치료를 뜻하지 않습니다. 성분·제품·목적·국가별 허가와 근거를 각각 확인해야 합니다. 특정 HA 제품의 볼 피부 매끄러움 자료를 다른 제품이나 건조증 치료에 그대로 적용할 수 없습니다.','These names do not describe one standardized treatment. Check the ingredient, product, purpose, country-specific authorization and evidence. Cheek-smoothness data for a specific HA product cannot be generalized to other products or dry-skin treatment.','这些名称并不代表一种标准治疗，应逐一确认成分、产品、用途、各国许可与证据。某一 HA 产品的面颊平滑度资料不能推广至其他产品或干燥症治疗。'],question:['정확한 제품명·성분·허가된 목적은 무엇인가요? 주사 없이 관리할 대안과 부작용은요?','What exact product, ingredient and authorized purpose are involved? What are the non-injection alternatives and adverse effects?','具体产品、成分和获批用途是什么？非注射替代方案及不良反应有哪些？'],url:'https://www.fda.gov/medical-devices/recently-approved-devices/skinvive-juvederm-p110033s059'}
];
