import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
const records=[],out='qa-results';await mkdir(out,{recursive:true});
const server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'inherit'});
let browser,page;
const check=(name,fn)=>async()=>{try{await fn();records.push({name,passed:true});console.log('PASS',name);}catch(error){records.push({name,passed:false,error:String(error)});throw error;}};
try{
 for(let n=0;n<50;n++){try{if((await fetch('http://127.0.0.1:8080/')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1040},acceptDownloads:true});
 page=await context.newPage();const requests=[],errors=[];page.on('request',r=>requests.push({url:r.url(),method:r.method()}));page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('http://127.0.0.1:8080/');await page.waitForFunction(()=>document.querySelector('#status').textContent.length>0);
 await check('WebGL demo boots with no JavaScript errors',async()=>{const engineMode=await page.locator('#engine-mode').innerText();if(!engineMode.includes('WEBGL')){const reason=await page.evaluate(async()=>{try{const {FaceView}=await import('./engine.js');new FaceView(document.createElement('canvas'));return 'Created second view';}catch(e){return String(e);}});throw Error('WebGL initialization failed: '+reason);}assert.match(await page.locator('#geometry-count').innerText(),/2537/);assert.equal(errors.length,0);})();
 await check('No face SDK/model request before consent and upload',async()=>{assert.equal(requests.filter(r=>r.url.includes('/vendor/')).length,0);assert.ok(await page.locator('#upload').isDisabled());})();
 await check('Real GPU-API-rendered demo changes after rotation',async()=>{const b=await page.locator('#face3d').screenshot();await page.locator('#face3d').focus();await page.keyboard.press('ArrowRight');const a=await page.locator('#face3d').screenshot();assert.ok(!b.equals(a));})();
 // Official public sample is a transient test input. Never included in source/dist artifacts.
 const sample=await fetch('https://storage.googleapis.com/mediapipe-assets/portrait.jpg',{signal:AbortSignal.timeout(30000)});assert.ok(sample.ok,'Official sample could not download');const portrait=Buffer.from(await sample.arrayBuffer());
 await page.locator('#consent').check();await page.locator('#photo').setInputFiles({name:'official-test-portrait.jpg',mimeType:'image/jpeg',buffer:portrait});
 await check('Actual MediaPipe inference creates a 468-vertex photo surface',async()=>{await page.waitForFunction(()=>document.querySelector('#geometry-count').textContent.startsWith('468 '),{},{timeout:60000});assert.match(await page.locator('#model-label').innerText(),/추정/);})();
 await check('SDK, WASM and model are requested from the same origin',async()=>{const v=requests.filter(r=>r.url.includes('/vendor/'));assert.ok(v.some(r=>r.url.includes('.wasm')));assert.ok(v.some(r=>r.url.includes('face_landmarker.task')));assert.ok(v.every(r=>new URL(r.url).origin==='http://127.0.0.1:8080'));})();
 await page.locator('#face3d').focus();await page.keyboard.press('Enter');
 await check('Photo mesh deformation and original/simulation comparison',async()=>{assert.equal(await page.locator('#points button').count(),1);await page.locator('#strength').evaluate(e=>{e.value='90';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#clay').click();const after=await page.locator('#face3d').screenshot();await page.locator('#before').click();const before=await page.locator('#face3d').screenshot();assert.ok(!after.equals(before));await page.locator('#after').click();})();
 await check('A/B/C stores and restores actual editable point state',async()=>{await page.locator('#save').click();await page.locator('#reset').click();assert.equal(await page.locator('#points button').count(),0);await page.locator('[data-slot="0"]').click();assert.equal(await page.locator('#points button').count(),1);assert.equal(await page.locator('#strength').inputValue(),'90');})();
 await check('Treatment information requires an answered safety question',async()=>{await page.locator('#skin-tab').click();await page.locator('[name=concern][value=dry]').check();assert.equal(await page.locator('.topic').count(),0);await page.locator('#risk').selectOption('no');assert.ok(await page.locator('.topic').count()>=2);await page.locator('#risk').selectOption('yes');assert.equal(await page.locator('.topic').count(),0);assert.ok(await page.locator('#options .warning').isVisible());})();
 await check('Korean, English and Chinese switch without resetting results',async()=>{for(const lang of ['en','zh','ko']){await page.locator('#language').selectOption(lang);assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.match(await page.locator('#geometry-count').innerText(),/468/);}})();
 await check('Exported discussion notes contain no photo or landmark data',async()=>{const d=page.waitForEvent('download');await page.locator('#report').click();const download=await d;const notes=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(notes.schema,'aestyve-discussion-notes/1');assert.equal(notes.selfReportedSafety,'yes');assert.equal(notes.educationalTopics.length,0);assert.ok(!('photo' in notes));assert.ok(!('landmarks' in notes));})();
 await check('Deletion clears photo, notes and saved looks, resets geometry count',async()=>{await page.locator('#erase').click();assert.match(await page.locator('#geometry-count').innerText(),/2537/);assert.equal(await page.locator('#slots img').count(),0);assert.ok(!await page.locator('#consent').isChecked());assert.ok(await page.locator('#upload').isDisabled());})();
 await check('Watermarked comparison PNG is a real browser download',async()=>{const d=page.waitForEvent('download');await page.locator('#download').click();const download=await d;assert.equal(download.suggestedFilename(),'Aestyve-visual-comparison.png');const bytes=await readFile(await download.path());assert.equal(bytes.subarray(1,4).toString(),'PNG');assert.ok(bytes.length>10000);})();
 await check('No application POST, remote image transmission or persistent face storage',async()=>{assert.ok(requests.every(r=>r.method==='GET'));assert.ok(requests.filter(r=>!r.url.startsWith('http://127.0.0.1:8080/')).every(r=>r.url.startsWith('https://cdn.jsdelivr.net/gh/projectnoonnu/')));assert.deepEqual(await page.evaluate(()=>[localStorage.length,sessionStorage.length]),[0,0]);})();
 await page.screenshot({path:out+'/desktop-demo.png',fullPage:true});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();await m.goto('http://127.0.0.1:8080/');await m.waitForFunction(()=>document.querySelector('#status').textContent.length>0);
 await check('Mobile width and touch shape-point interaction',async()=>{assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await m.locator('#face3d').scrollIntoViewIfNeeded();const r=await m.locator('#face3d').boundingBox();await m.touchscreen.tap(r.x+r.width*.5,r.y+r.height*.58);assert.equal(await m.locator('#points button').count(),1);})();
 await m.screenshot({path:out+'/mobile-demo.png',fullPage:true});await mobile.close();
 await check('No JavaScript runtime errors during complete flow',async()=>assert.equal(errors.length,0))();
} catch(error){records.push({name:'Flow completion',passed:false,error:String(error)});console.error(error);process.exitCode=1;if(page)await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});}
finally{await writeFile(out+'/report.json',JSON.stringify({timestamp:new Date().toISOString(),scope:'Technical smoke tests with official sample portrait; not clinical accuracy, not physical-device validation. SwiftShader executes WebGL APIs in software.',records},null,2));await browser?.close();server.kill();}
