import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const out='qa-results',records=[];await mkdir(out,{recursive:true});
const check=async(name,fn)=>{try{await fn();records.push({name,passed:true});console.log('PASS',name);}catch(error){records.push({name,passed:false,error:String(error)});throw error;}};
let browser,page;
try{
 // Public Google sample stays in transient memory. Never write it to an artifact.
 const response=await fetch('https://storage.googleapis.com/mediapipe-assets/portrait.jpg',{signal:AbortSignal.timeout(30000)});
 assert.ok(response.ok,'Official test portrait unavailable');const portrait=Buffer.from(await response.arrayBuffer());
 browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true,offline:true});
 page=await context.newPage();const errors=[],requests=[];
 page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
 await page.goto(pathToFileURL(resolve('standalone/Aestyve-Face-Lab.html')).href);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.length>0||!document.querySelector('#local-error').hidden);
 await check('Single HTML boots directly from file:// with network offline',async()=>{assert.ok(await page.locator('#local-error').isHidden());assert.match(await page.locator('#geometry-count').innerText(),/2537/);assert.ok(await page.locator('#upload').isDisabled());assert.equal(errors.length,0);});
 await check('Three embedded gel photos render without an HTTP server',async()=>{await page.waitForFunction(()=>[...document.querySelectorAll('.gel img')].every(i=>i.complete&&i.naturalWidth>0));assert.equal(await page.locator('.gel img').count(),3);});
 await check('Depth-bearing demo rotates and returns to front',async()=>{const before=await page.locator('#face3d').screenshot();await page.locator('#face3d').focus();await page.keyboard.press('ArrowRight');const after=await page.locator('#face3d').screenshot();assert.ok(!before.equals(after));await page.locator('#home').click();});
 await page.locator('#consent').check();await page.locator('#photo').setInputFiles({name:'transient-official-portrait.jpg',mimeType:'image/jpeg',buffer:portrait});
 await check('Embedded real MediaPipe model produces 468-vertex photo surface offline',async()=>{await page.waitForFunction(()=>document.querySelector('#geometry-count').textContent.startsWith('468 '),{},{timeout:60000});assert.match(await page.locator('#model-label').innerText(),/추정/);assert.equal(errors.length,0);});
 await check('Uploaded-photo deformation and original comparison work',async()=>{await page.locator('#face3d').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#points button').count(),1);await page.locator('#strength').evaluate(e=>{e.value='90';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#clay').click();const after=await page.locator('#face3d').screenshot();await page.locator('#before').click();const before=await page.locator('#face3d').screenshot();assert.ok(!before.equals(after));await page.locator('#after').click();});
 await check('A/B/C saved look restores editable strength and point',async()=>{await page.locator('#save').click();await page.locator('#reset').click();assert.equal(await page.locator('#points button').count(),0);await page.locator('[data-slot="0"]').click();assert.equal(await page.locator('#points button').count(),1);assert.equal(await page.locator('#strength').inputValue(),'90');});
 await check('Korean English Chinese controls retain current 3D',async()=>{for(const lang of ['en','zh','ko']){await page.locator('#language').selectOption(lang);assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.match(await page.locator('#geometry-count').innerText(),/468/);}});
 await check('Concern information is withheld for unanswered or positive safety flag',async()=>{await page.locator('#skin-tab').click();await page.locator('[name=concern][value=dry]').check();assert.equal(await page.locator('.topic').count(),0);await page.locator('#risk').selectOption('no');assert.ok(await page.locator('.topic').count()>=2);await page.locator('#risk').selectOption('yes');assert.equal(await page.locator('.topic').count(),0);assert.ok(await page.locator('#options .warning').isVisible());});
 await check('Discussion-notes JSON download excludes photograph and landmarks',async()=>{const event=page.waitForEvent('download');await page.locator('#report').click();const download=await event;const data=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(data.schema,'aestyve-discussion-notes/1');assert.equal(data.selfReportedSafety,'yes');assert.equal(data.educationalTopics.length,0);assert.ok(!('photo' in data));assert.ok(!('landmarks' in data));});
 await check('Erase resets consent, face, looks, shape points and answers',async()=>{await page.locator('#erase').click();assert.match(await page.locator('#geometry-count').innerText(),/2537/);assert.equal(await page.locator('#slots img').count(),0);assert.equal(await page.locator('#points button').count(),0);assert.equal(await page.locator('input[name=concern]:checked').count(),0);assert.equal(await page.locator('#risk').inputValue(),'unknown');assert.ok(await page.locator('#upload').isDisabled());});
 await check('Watermarked PNG comparison is downloadable from file://',async()=>{const event=page.waitForEvent('download');await page.locator('#download').click();const download=await event;assert.equal(download.suggestedFilename(),'Aestyve-visual-comparison.png');const data=await readFile(await download.path());assert.equal(data.subarray(1,4).toString(),'PNG');assert.ok(data.length>10000);});
 await check('No network photo/model transmission; only optional external font GETs',async()=>{assert.ok(requests.every(r=>r.method==='GET'));const remote=requests.filter(r=>/^https?:/.test(r.url));assert.ok(remote.every(r=>r.url.startsWith('https://cdn.jsdelivr.net/gh/projectnoonnu/')),JSON.stringify(remote));assert.deepEqual(await page.evaluate(()=>[localStorage.length,sessionStorage.length]),[0,0]);});
 // Save evidence images only after clearing the official portrait.
 await page.screenshot({path:out+'/standalone-desktop.png',fullPage:true});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,offline:true});const m=await mobile.newPage();await m.goto(pathToFileURL(resolve('standalone/Aestyve-Face-Lab.html')).href);await m.waitForFunction(()=>document.querySelector('#status').textContent.length>0);
 await check('Responsive width and touch placement in mobile emulation',async()=>{assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await m.locator('#face3d').scrollIntoViewIfNeeded();const rect=await m.locator('#face3d').boundingBox();await m.touchscreen.tap(rect.x+rect.width*.5,rect.y+rect.height*.58);assert.equal(await m.locator('#points button').count(),1);});
 await m.screenshot({path:out+'/standalone-mobile.png',fullPage:true});await mobile.close();
 await check('No JavaScript runtime errors throughout the standalone flow',async()=>assert.equal(errors.length,0));
}catch(error){console.error(error);records.push({name:'Standalone flow completion',passed:false,error:String(error)});process.exitCode=1;}
finally{await writeFile(out+'/standalone-report.json',JSON.stringify({timestamp:new Date().toISOString(),scope:'Single HTML file:// smoke tests with network offline and real MediaPipe inference on a transient official Google sample. SwiftShader WebGL; not physical hardware or clinical validation.',records},null,2));await browser?.close();}
